##
##	COMOE NETWORKS COPYRIGHTS
##
##	MAKEFILE FOR SOCK
##

### PROGRAM NAME
PROG_NAME=sock
EXEC=$(PROG_NAME)
### ARCHIVE PARAMS
#DIR=$(PROG_NAME)
DIR=yasock
ARCHIVE_NAME=$(PROG_NAME).tgz
ARCHIVE_DEST=$(HOME)/archive

### LIST OF SOURCE FILES
SRC=main.c server.c client.c socket_opt.c
### LIST OF INCLUDE FILES
INC=cnsock.h
### LIST OF OBJECT FILES
OBJS=${SRC:%.c=%.o}

### DEV FLAGS FOR COMPILATION AND LINKING
CC_OPT_DEV= -g2 -Wall -Werror -D_DEFAULT_SOURCE
CFLAGS_DEV= $(CC_OPT_DEV) -I$(HOME)/include -I/opt/comoenetworks/include
LDFLAGS_DEV= $(CC_OPT_DEV) -L$(HOME)/lib -L/opt/comoenetworks/lib
### PROD FLAGS FOR COMPILATION AND LINKING
CC_OPT_PROD= -O2 -Wall -Werror -D_DEFAULT_SOURCE
CFLAGS_PROD= $(CC_OPT_PROD) -I$(HOME)/include -I/opt/comoenetworks/include
LDFLAGS_PROD= $(CC_OPT_PROD) -L$(HOME)/lib -L/opt/comoenetworks/lib

### TARGETS
.PHONY: all clean
all:
	@echo "\n[Makefile for $(PROG_NAME)]: Unknown action. Cannot proceed." && false


dev: CFLAGS=$(CFLAGS_DEV)
dev: LDFLAGS=$(LDFLAGS_DEV)
dev: $(EXEC)

prod: CFLAGS=$(CFLAGS_PROD)
prod: LDFLAGS=$(LDFLAGS_PROD)
prod: $(EXEC)

$(EXEC): $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS) 

%.o: %.c $(INC)
	$(CC) $(CFLAGS) -o $@ -c $<

archive: clean
	cd .. && tar -zcvf $(ARCHIVE_DEST)/$(ARCHIVE_NAME) $(DIR) && ls -l $(ARCHIVE_DEST)/$(ARCHIVE_NAME)
update:
	cd .. && tar -zxf $(ARCHIVE_DEST)/$(ARCHIVE_NAME)

clean:
	/bin/rm -f *~ $(EXEC) $(OBJS) *core a.out
